#! user/bin/evn python 3
# coding : utf-8

import pygame


pygame.init()


display_width = 500
display_height = 400

gameDisplay = pygame.display.set_mode((display_width,display_height))
pygame.display.set_caption('Aidez Mcgyver')

black = (0,0,0)
white = (255,255,255)

clock = pygame.time.Clock()
Mort = False
arImg = pygame.image.load('macgyver.png')

def car(x,y):
    gameDisplay.blit(arImg, (x,y))

x =  (display_width * 0.45)
y = (display_height * 0.8)

while not Mort:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            Mort = True

    gameDisplay.fill(black)
    car(x,y)

        
    pygame.display.update()
    clock.tick(60)

pygame.quit()
quit()
